### ISSUE TITLE
cubestore S3 credentials regression in v0.35.17

### ISSUE THREAD

**Issue by adamstruck** [cube-js/cube#8163]
**Describe the bug**

When I attempted to upgrade from v0.35.14 I started to see this error:

```
2024-04-17T18:17:19.257Z INFO  [cubestored] <pid:1> Cube Store version 0.35.17
2024-04-17T18:17:19.260Z INFO  [cubestore::http::status] <pid:1> Serving status probes at 0.0.0.0:3031
thread 'main' panicked at /build/cubestore/cubestore/src/config/mod.rs:1816:86:
called `Result::unwrap()` on an `Err` value: CubeError { message: "Failed to create S3 credentials: attohttpc: Json Error: expected value at line 1 column 1", backtrace: "", cause: Internal }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/result.rs:1649:5
   3: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   4: cubestore::config::injection::Injector::get_service::{{closure}}
   5: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   6: cubestore::config::injection::Injector::get_service::{{closure}}
   7: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   8: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   9: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  10: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  11: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  12: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  13: cubestored::main::{{closure}}
  14: tokio::runtime::park::CachedParkThread::block_on
  15: tokio::runtime::runtime::Runtime::block_on
  16: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Version:**
v0.35.17

**Comment by adamstruck** [comment]
I assume this is due to one of these PRs:

https://github.com/cube-js/cube/pull/6019
https://github.com/cube-js/cube/pull/8158

**Comment by ovr** [comment]
Hello @adamstruck ,

Did you specify both `CUBESTORE_AWS_ACCESS_KEY_ID` & `CUBESTORE_AWS_SECRET_ACCESS_KEY` or only `CUBESTORE_AWS_SECRET_ACCESS_KEY`?

Thanks

**Comment by adamstruck** [comment]
I only set `CUBESTORE_AWS_CREDS_REFRESH_EVERY_MINS`. The credentials used to be picked up automatically from the pod / instance. We have been running various versions of cube for the past year and this is the first time it has been a problem.

**Comment by ovr** [comment]
Is it correct that you are using STS (AWS_WEB_IDENTITY_TOKEN_FILE), IAM?

> "Failed to create S3 credentials: attohttpc: Json Error: expected value at line 1 column 1

This error comes from fallback logic that is trying to resolve auth from magic IP 169.254.169.254. It's a fallback variant.

**Comment by adamstruck** [comment]
@ovr do you think this is something you will be able to fix soon?

**Comment by ovr** [comment]
@adamstruck I tried to find out what had changed in the library, but I could not find anything that can affect you.

**Comment by adamstruck** [comment]
Did cube start doing anything differently starting in that version?

**Comment by adamstruck** [comment]
Or maybe it is this line: 

https://github.com/cube-js/cube/pull/6019/files#diff-28d0e549290be2ac2e69b3c1da8d7e05aa0f58db287f72872c53c93c496913a0R57

I am not familiar with rust dependency management, but this seems to imply that not all features are being included after the bump?

**Comment by adamstruck** [comment]
I still am running into this issue with the latest version: v0.35.22

**Comment by ovr** [comment]
We didn't start doing anything differently. I reviewed all changes in the `rust-s3` crate, and I didn't find anything that could cause this error.

In the production, we use IAM, and it works correctly.

You can check it from the pod, via curl to `http://169.254.169.254/latest/meta-data/iam/security-credentials`.

Do you see any error? It should be a correct JSON.

Thanks

**Comment by adamstruck** [comment]
I think you are on to something...

```
$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
empty role
```

`AWS_ROLE_ARN` is set in my env and so is `AWS_WEB_IDENTITY_TOKEN_FILE`. 

Any ideas?

**Comment by adamstruck** [comment]
Based on https://github.com/durch/rust-s3/blob/v0.32.0/aws-creds/src/credentials.rs#L173 it looks like `aws-creds` with feature `"http-credentials"` is needed for this type of auth to work.

**Comment by ChrisLahaye** [comment]
> I only set `CUBESTORE_AWS_CREDS_REFRESH_EVERY_MINS`. The credentials used to be picked up automatically from the pod / instance. We have been running various versions of cube for the past year and this is the first time it has been a problem.
> 
> I am able to run v0.35.16 without issue.

We are experiencing the same issue although we get the following error,
```
2024-04-25T14:43:31.783Z ERROR [cubestore::cluster] <pid:1> Error: CubeError { message: "AWS S3 error: serde xml: custom: missing field `Name`", backtrace: "", cause: Internal }
```

**Comment by ovr** [comment]
Right now, it's not possible to use the 0.33 release because it has bugs
At the same time, 0.34-rc has a problem with large file uploading because it doesn't control a number of parallels put(s), which causes high memory usage.

🫠

At the same time, the official SDK from AWS has problems.

@adamstruck

So, I backported the fix from https://github.com/durch/rust-s3/issues/286 in https://github.com/cube-js/cube/pull/8195/files

**Comment by goncaloacteixeira** [comment]
@ovr the issue still persists on my side, tested v0.35.24

**Comment by ChrisLahaye** [comment]
@ovr the issue persists here as well, although it it slightly different it was introduced at the same release.

```
024-04-26T13:38:47.733Z INFO  [cubestored] <pid:1> Cube Store version 0.35.24
2024-04-26T13:38:47.740Z INFO  [cubestore::http::status] <pid:1> Serving status probes at 0.0.0.0:3031
thread 'main' panicked at /build/cubestore/cubestore/src/config/mod.rs:1971:34:
called `Result::unwrap()` on an `Err` value: CubeError { message: "AWS S3 error: serde xml: custom: missing field `Name`", backtrace: "", cause: Internal }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/result.rs:1649:5
   3: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   4: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   5: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   6: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   7: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   8: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   9: cubestored::main::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by adamstruck** [comment]
@ovr I am still seeing errors with v0.35.24

```
2024-04-26T16:12:16.689Z INFO  [cubestored] <pid:1> Cube Store version 0.35.24
thread 'main' panicked at /build/cubestore/cubestore/src/config/mod.rs:1816:86:
called `Result::unwrap()` on an `Err` value: CubeError { message: "Failed to create S3 credentials: attohttpc: Json Error: expected value at line 1 column 1", backtrace: "", cause: Internal }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/result.rs:1649:5
   3: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   4: cubestore::config::injection::Injector::get_service::{{closure}}
   5: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   6: cubestore::config::injection::Injector::get_service::{{closure}}
   7: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   8: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   9: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  10: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  11: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  12: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  13: cubestored::main::{{closure}}
  14: tokio::runtime::park::CachedParkThread::block_on
  15: tokio::runtime::runtime::Runtime::block_on
  16: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by adamstruck** [comment]
@ovr could the `from_sts` method just be reverted to what was in 0.26.3 (https://github.com/durch/rust-s3/blob/0.26.3/aws-creds/src/credentials.rs#L139-L141)?

**Comment by adamstruck** [comment]
I hacked around this issue by authenticating via STS in a separate process and storing the returned credentials in `~/.aws/credentials` so that cubestore is able to use them.

**Comment by paveltiunov** [comment]
@adamstruck If it's still an issue, please feel free to provide PRs to https://github.com/cube-js/rust-s3 and to the Cube Store itself.

**Comment by adamstruck** [comment]
@ovr looks the the issue is fixed `v0.35.34` - thank you for finding a fix for this!

**Comment by ovr** [comment]
@adamstruck Thank you for testing then I am going to close this issue.

**Comment by danielli-ziprecruiter** [comment]
I'm still experience this issue in `v0.35.38` with the same error message in this [comment](https://github.com/cube-js/cube/issues/8163#issuecomment-2079422971).

**Comment by lukethomas-acsg** [comment]
Hi everyone, I've just been doing a bit of diagnosis on this. I think what might be happening here is that AWS STS credentials aren't actually enabled in release builds of the rust-s3 library. 

Looking at the following line, it doesn't look like the "http-credentials" feature is enabled: 
https://github.com/cube-js/rust-s3/blob/cubestore-0.32.3-backport/rust-s3/Cargo.toml#L21

However, it actually is enabled in the dev-dependencies section of the same file (https://github.com/cube-js/rust-s3/blob/cubestore-0.32.3-backport/rust-s3/Cargo.toml#L75). 

I suspect that the error message in this [comment](https://github.com/cube-js/cube/issues/8163#issuecomment-2079422971) actually isn't related to getting credentials at all but is produced because the instance that the container is running on has IMDSv1 enabled. This allows the rust-s3 library to retrieve credentials from the underlying instance. The role associated with these credentials likely doesn't have the correct S3 permissions and as a result, we get this error message. 

This might be as simple to fix as enabling the "http-credentials" feature on the "aws-creds" dependency in the "rust-s3" crate but I don't have a good enough knowledge of the project as a whole to know whether this is all that would need to be done.

**Comment by Graphmaxer** [comment]
Hello, for me it's working since `v0.35.34` even on `v0.35.38`, but since `0.35.67`, i have a new error related to certificates : 

```
   6:     0x561997708288 - std::panicking::rust_panic_with_hook::h48fa132e308b8b90
   7:     0x561997708162 - std::panicking::begin_panic_handler::{{closure}}::h25d6c93d3d1459db
   8:     0x561997706cb6 - std::sys_common::backtrace::__rust_end_short_backtrace::h34a894d5da7b6896
   9:     0x561997707eb4 - rust_begin_unwind
  10:     0x561994d17845 - core::panicking::panic_fmt::he5ea86dee9f7da0f
  11:     0x561994d17d93 - core::result::unwrap_failed::ha5dadee551c1996c
  12:     0x56199518f816 - cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}::h4a771688ba4a751f
  13:     0x5619951a3ac0 - cubestore::config::injection::Injector::get_service_typed::{{closure}}::h2276ec6abf3c6f72
  14:     0x56199518fcd8 - cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}::h5095b26dd8a16e01
  15:     0x5619951a770e - cubestore::config::injection::Injector::get_service_typed::{{closure}}::h69190a124b75933a
  16:     0x561995194bb1 - cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}::hab66cda907be12eb
  17:     0x5619951a94ee - cubestore::config::injection::Injector::get_service_typed::{{closure}}::h8946018459a06bcb
  18:     0x5619951b4578 - cubestored::main::{{closure}}::h776bfc975c50803d
  19:     0x561995166ce9 - tokio::runtime::park::CachedParkThread::block_on::h6d4fbbd2602824bb
  20:     0x561994f14778 - tokio::runtime::runtime::Runtime::block_on::h7b407fd4e0e449eb
  21:     0x561994e91f44 - cubestored::main::h850a1ce0e17c8893
  22:     0x56199508db03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1c57aaaeac5e12c4
  23:     0x561995156bc9 - std::rt::lang_start::{{closure}}::h1e897efafc8e83e2
  24:     0x5619976fc781 - std::rt::lang_start_internal::h609d11868d4e20c8
  25:     0x561994e92605 - main
  26:     0x7f5f569cc24a - <unknown>
  27:     0x7f5f569cc305 - __libc_start_main
  28:     0x561994d69611 - _start
  29:                0x0 - <unknown>
```

Maybe it's related to this small change https://github.com/cube-js/cube/pull/8554/files
It's working on `v0.35.66`, thanks for the help

**Comment by Graphmaxer** [comment]
Fixed on the `v0.35.68`, thanks :) https://github.com/cube-js/cube/pull/8571

**Comment by revvysh** [comment]
Still facing this issue on Cube Store version 1.1.8
> 2024-12-07T06:17:31.673Z INFO  [cubestored] <pid:7> Cube Store version 1.1.8
2024-12-07T06:17:31.677Z INFO  [cubestore::http::status] <pid:7> Serving status probes at 0.0.0.0:3031
thread 'main' panicked at /build/cubestore/cubestore/src/config/mod.rs:1844:86:
called `Result::unwrap()` on an `Err` value: CubeError { message: "Failed to create S3 credentials: Could not get valid credentials from STS, ENV, Profile or Instance metadata", backtrace: "", cause: Internal }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   4: cubestore::config::injection::Injector::get_service::{{closure}}
   5: cubestore::config::injection::Injector::register::{{closure}}::{{closure}}::{{closure}}
   6: cubestore::config::injection::Injector::get_service::{{closure}}
   7: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   8: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   9: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  10: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  11: cubestore::config::Config::configure_common::{{closure}}::{{closure}}
  12: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
  13: cubestore::config::injection::Injector::get_service_typed::{{closure}}
  14: cubestored::main::{{closure}}
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::runtime::Runtime::block_on
  17: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace

**Comment by anurag-bluepencil** [comment]
> > I only set `CUBESTORE_AWS_CREDS_REFRESH_EVERY_MINS`. The credentials used to be picked up automatically from the pod / instance. We have been running various versions of cube for the past year and this is the first time it has been a problem.
> > I am able to run v0.35.16 without issue.
> 
> We are experiencing the same issue although we get the following error,
> 
> ```
> 2024-04-25T14:43:31.783Z ERROR [cubestore::cluster] <pid:1> Error: CubeError { message: "AWS S3 error: serde xml: custom: missing field `Name`", backtrace: "", cause: Internal }
> ```
@ChrisLahaye any solution so far you got for the same  ?
